Delegation/Components/NavigationMenuViewComponent.cs
using Delegation.Models.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Delegation.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IBusinessTripRepository _repository;

        public NavigationMenuViewComponent(IBusinessTripRepository repository)
        {
            _repository = repository;
        }

        public IViewComponentResult Invoke() 
            => View(_repository.BusinessTrips
                .Select(t=>t.Project.Symbol)
                .Distinct()
                .OrderBy(t=>t));
    }
}

Delegation/Controllers/BusinessTripController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Delegation.Models.Repositories;
using Delegation.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Delegation.Controllers
{
    public class BusinessTripController : Controller
    {
        private IBusinessTripRepository _repository;
        public int PageSize = 2;

        public BusinessTripController(IBusinessTripRepository repository)
        {
            _repository = repository;
        }

        public ViewResult List(string symbol, int page = 1)
            => View(new BusinessTripViewModel
            {
                BusinessTrips = _repository.BusinessTrips
                .Where(t=>symbol == null || t.Project.Symbol == symbol)
                .OrderBy(t => t.BusinessTripID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = _repository.BusinessTrips.Count()
                },
                CurrentProject = symbol
            });
    }
}

Delegation/Views/Shared/Components/NavigationMenu/Default.cshtml
@model IEnumerable<string>

    <form asp-controller="BusinessTrip" asp-action="List" method="post">
        <label>Temat</label>
        <select id="symbol" name="symbol" class="form-control">
            @foreach (var symbol in Model)
            {
                <option value="@symbol">@symbol</option>
            }
        </select>
        <br>
        <button type="submit" class="btn btn-secondary">Zastosuj</button>
    </form>