Delegation/Models/BusinessTrip.cs
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Delegation.Models
{
    [Serializable]
    public class BusinessTrip
    {
        [Display(Name = "BusinessTripID")]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int BusinessTripID { get; set; }

        [Display(Name = "Wyjazd")]
        public DateTime DepartureDate { get; set; }

        [Display(Name = "Przyjazd")]
        public DateTime ArrivalDate { get; set; }

        [Display(Name = "Kierowca")]
        public Driver Driver { get; set; }

        [Display(Name = "Temat")]
        public Project Project { get; set; }

        [Display(Name = "Dysponent")]
        public Employee Keeper { get; set; }

        [Display(Name = "Miejsce docelowe")]
        public Destination Destination { get; set; }

        [Display(Name = "Samochód")]
        public Car Car { get; set; }

        [Display(Name = "Stan licznika początkowy")]
        public int InitialMeter { get; set; }

        [Display(Name = "Stan licznika końcowy")]
        public int FinalMeter { get; set; }

        [Display(Name = "Liczba przejechanych km")]
        public int Distance => FinalMeter - InitialMeter;

        public KilometersCard KilometersCard { get; set; }
    }
}

Delegation/Models/ViewModels/BusinessTripViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Delegation.Models.ViewModels
{
    public class BusinessTripViewModel
    {
        public IEnumerable<BusinessTrip> BusinessTrips { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentProject { get; set; }
    }
}

Delegation/Controllers/BusinessTripController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Delegation.Models.Repositories;
using Delegation.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Delegation.Controllers
{
    public class BusinessTripController : Controller
    {
        private IBusinessTripRepository _repository;
        public int PageSize = 2;

        public BusinessTripController(IBusinessTripRepository repository)
        {
            _repository = repository;
        }

        public ViewResult List(string symbol, int page = 1)
            => View(new BusinessTripViewModel
            {
                BusinessTrips = _repository.BusinessTrips
                .Where(t=>symbol == null || t.Project.Symbol == symbol)
                .OrderBy(t => t.BusinessTripID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = _repository.BusinessTrips.Count()
                },
                CurrentProject = symbol
            });
    }
}

Delegation/Controllers/ManageBusinessTripController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Delegation.Models;
using Delegation.Models.Repositories;
using Delegation.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Delegation.Controllers
{
    public class ManageBusinessTripController : Controller
    {
        IBusinessTripRepository _repository;
        
        public ManageBusinessTripController(IBusinessTripRepository repository)
            => _repository = repository;

        public ViewResult Index() => View(_repository.BusinessTrips);

        public ViewResult Edit(int businessTripID)
            => View(new ManageBusinessTripViewModel
            {
                BusinessTrip = _repository.BusinessTrips
                    .FirstOrDefault(t => t.BusinessTripID == businessTripID),
                Drivers = GetSelectList(_repository.BusinessTrips
                    .Select(d => d.Driver)
                    .Distinct()
                    .OrderBy(d => d.EmployeeID)),
                Projects = GetSelectList(_repository.BusinessTrips
                    .Select(p=>p.Project)
                    .Distinct()
                    .OrderBy(p=>p.ProjectID))
            });

        private IEnumerable<SelectListItem> GetSelectList(IEnumerable<Driver> drivers)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            foreach(var d in drivers)
            {
                items.Add(new SelectListItem { Text = d.ToString(), Value = d.ToString() });
            }
            return items;
        }
        private IEnumerable<SelectListItem> GetSelectList(IEnumerable<Project> projects)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            foreach (var p in projects)
            {
                items.Add(new SelectListItem { Text = p.ToString(), Value = p.ToString() });
            }
            return items;
        }
    }
}

Delegation/Views/BusinessTrip/List.cshtml
@model BusinessTripViewModel

<div class="row">
    <div class="align-self-center">
        Strona:
    </div>
    <div page-model="@Model.PagingInfo" page-action="List" page-classes-enabled="true"
         page-class="btn" page-class-normal="btn secondary"
         page-class-selected="btn btn-primary" class="btn-group pull-right m-1"
         page-url-project="@Model.CurrentProject">
    </div>
    
    </div>
    


<table class="table table-striped table-bordered table-sm">
    <tr>
        <th class="text-center">ID</th>
        <th class="text-center">Temat</th>
        <th class="text-center">Cel wyjazdu</th>
        <th class="text-center">Data wyjazdu</th>
        <th class="text-center">Data powrotu</th>
        <th class="text-center">Kierowca</th>
        <th class="text-center">Dysponent</th>
        <th class="text-center">Samochód</th>
        <th class="text-center">Dystans</th>
    </tr>

    @foreach (var t in @Model.BusinessTrips)
    {
    <tr>
        <td class="text-rigth mr-2">@t.BusinessTripID</td>
        <td class="text-center">@t.Project</td>
        <td class="text-center">@t.Destination</td>
        <td class="text-center">@t.DepartureDate.ToShortDateString()</td>
        <td class="text-center">@t.ArrivalDate.ToShortDateString()</td>
        <td class="text-center">@t.Driver</td>
        <td class="text-center">@t.Keeper</td>
        <td class="text-center">@t.Car</td>
        <td class="text-center">@t.Distance</td>
    </tr>
    }
</table>

<div class="float-right"><a asp-action="Index" asp-controller="ManageBusinessTrip" class="btn btn-primary">Edytuj Listę</a></div>